# Generated by Django 2.2.6 on 2019-10-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeData',
            fields=[
                ('mentee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('isactive', models.TextField(blank=True, db_column='isActive', null=True)),
                ('isavailable', models.TextField(blank=True, db_column='isAvailable', null=True)),
            ],
            options={
                'db_table': 'mentee_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MentorData',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('isactive', models.TextField(blank=True, db_column='isActive', null=True)),
                ('isavailable', models.TextField(blank=True, db_column='isAvailable', null=True)),
            ],
            options={
                'db_table': 'mentor_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MentorMenteeAssoc',
            fields=[
                ('mentor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mentee_id', models.IntegerField()),
                ('match_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentor_mentee_assoc',
                'managed': False,
            },
        ),
    ]
