# Generated by Django 2.2.6 on 2019-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menteeData',
            fields=[
                ('mentee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mentee',
            },
        ),
        migrations.CreateModel(
            name='menteeRegistrationData',
            fields=[
                ('mentee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comm_plat', models.CharField(blank=True, max_length=5, null=True)),
                ('desire_dream', models.CharField(blank=True, max_length=250, null=True)),
                ('have_mentor', models.CharField(blank=True, max_length=250, null=True)),
                ('desc_yourslf', models.CharField(blank=True, max_length=250, null=True)),
                ('major_chall', models.CharField(blank=True, max_length=250, null=True)),
                ('ideal_mentor', models.CharField(blank=True, max_length=250, null=True)),
                ('any_else', models.CharField(blank=True, max_length=250, null=True)),
                ('race_req', models.CharField(blank=True, max_length=5, null=True)),
                ('race_details', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mentee_reg_data',
            },
        ),
    ]
