# Generated by Django 2.2.6 on 2019-10-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeregistrationdata',
            name='mentee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
