# Generated by Django 2.2.6 on 2019-10-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191020_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentorData',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_alter', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateTimeField()),
                ('pref_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('recent_employer', models.CharField(blank=True, max_length=50, null=True)),
                ('recent_position', models.CharField(blank=True, max_length=50, null=True)),
                ('languages', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'mentor',
            },
        ),
        migrations.CreateModel(
            name='mentorRegistrationData',
            fields=[
                ('mentor_id', models.AutoField(primary_key=True, serialize=False)),
                ('why_mentor', models.CharField(blank=True, max_length=5, null=True)),
                ('brief_summary', models.CharField(blank=True, max_length=250, null=True)),
                ('diff_situation', models.CharField(blank=True, max_length=250, null=True)),
                ('min_commit', models.CharField(blank=True, max_length=250, null=True)),
                ('min_avail', models.CharField(blank=True, max_length=250, null=True)),
                ('mentor_training', models.CharField(blank=True, max_length=250, null=True)),
                ('group_meetings', models.CharField(blank=True, max_length=250, null=True)),
                ('any_else', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'mentor_reg_data',
            },
        ),
    ]
