# Generated by Django 2.2.6 on 2019-10-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20191023_1733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menteedata',
            table='mentee',
        ),
    ]
