# Generated by Django 2.2.6 on 2019-10-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20191023_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menteeData',
        ),
    ]
