# Generated by Django 2.2.6 on 2019-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_delete_menteedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='menteeData',
            fields=[
                ('mentee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.IntegerField(blank=True, null=True)),
                ('isAvavilable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mentee_data',
            },
        ),
    ]
